name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: ⚙️ Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 📦 Install dependencies
        run: npm install

      - name: 🏗️ Build Astro
        run: npm run build

      - name: 🚀 Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "wsr" # thay bằng tên app Heroku của bạn
          heroku_email: "lenguyenductai208@mgail.com"  # email đăng ký Heroku
          usedocker: false
